name: Job summaries
on: push

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  log:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: |
          echo "## Example Title :rocket:" >> "${GITHUB_STEP_SUMMARY}"
          echo "- first line" >> "${GITHUB_STEP_SUMMARY}"
          echo "- second line" >> "${GITHUB_STEP_SUMMARY}"
