name: Matrix
on: push

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  print:
    strategy:
      matrix:
        os: [ubuntu-latest, window-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - run: echo "${RUNNER_OS}"
        shell: bash
